import '../models/appointment_model.dart';
import '../models/medical_record_model.dart';
import '../models/dependent_model.dart';
import '../models/medication_model.dart';
import '../models/vaccination_model.dart';
import '../models/consultation_model.dart';
import '../models/patient_model.dart';
import '../models/article_model.dart';
import '../models/notification_model.dart';

class MockDataService {
  static final List<AppointmentModel> appointments = [
    AppointmentModel(
      id: 1,
      doctorName: 'Dr. Sarah Jenkins',
      doctorSpecialty: 'Obstetrics & Gynecology',
      date: '2026-10-15',
      timeSlot: '10:30 AM',
      type: 'Video Consultation',
      reason: 'Luteal Phase Progesterone & Hormone Review',
      status: 'Confirmed',
      notes: 'Please bring recent pelvic ultrasound & thyroid panel.',
    ),
    AppointmentModel(
      id: 2,
      doctorName: 'Dr. Maya Patel',
      doctorSpecialty: 'Reproductive Endocrinology',
      date: '2026-10-22',
      timeSlot: '02:00 PM',
      type: 'In-Clinic Visit',
      reason: 'Fertility Window Assessment & AMH Check',
      status: 'Pending',
    ),
    AppointmentModel(
      id: 3,
      doctorName: 'Dr. Liam Vance',
      doctorSpecialty: 'Cardiologist & Women’s Heart Health',
      date: '2026-08-20',
      timeSlot: '11:00 AM',
      type: 'In-Clinic Visit',
      reason: 'Resting Blood Pressure & SpO2 Follow-up',
      status: 'Completed',
      notes: 'Blood pressure 118/76 mmHg. Heart rate variability optimal.',
    ),
  ];

  static final List<MedicalRecordModel> records = [
    MedicalRecordModel(
      id: 1,
      title: 'Hormone & Biomarker Panel Q3',
      category: 'Lab Results',
      date: 'Sep 10, 2026',
      doctorOrLab: 'Apex Diagnostic Labs',
      fileType: 'PDF',
      fileSize: '2.4 MB',
      summary: 'Estradiol 180 pg/mL, Progesterone 14.2 ng/mL, TSH 1.85 mIU/L. Values within optimal range for mid-luteal phase.',
      isSharedWithDoctor: true,
    ),
    MedicalRecordModel(
      id: 2,
      title: 'Pelvic & Ovarian Ultrasound Imaging',
      category: 'Scans & Imaging',
      date: 'Aug 24, 2026',
      doctorOrLab: 'St. Jude Women’s Imaging Center',
      fileType: 'PDF',
      fileSize: '8.1 MB',
      summary: 'Normal uterine morphology, bilateral follicular development intact, no cystic masses identified.',
      isSharedWithDoctor: true,
    ),
    MedicalRecordModel(
      id: 3,
      title: 'Prenatal Multivitamin & Vitamin D3 Prescription',
      category: 'Prescriptions',
      date: 'Aug 15, 2026',
      doctorOrLab: 'Dr. Sarah Jenkins',
      fileType: 'PDF',
      fileSize: '450 KB',
      summary: 'Active Methylfolate 800mcg + Vit D3 5000 IU daily with breakfast.',
      isSharedWithDoctor: true,
    ),
    MedicalRecordModel(
      id: 4,
      title: 'Longitudinal AI Health Twin Baseline Export',
      category: 'Clinical Summaries',
      date: 'Jul 28, 2026',
      doctorOrLab: 'FemSphere AI Bio-Twin Engine',
      fileType: 'PDF',
      fileSize: '1.9 MB',
      summary: 'AI Biological Twin Score: 92/100. Low cardiovascular risk (3%), regular 28-day cycle stability.',
      isSharedWithDoctor: true,
    ),
  ];

  static final List<DependentModel> dependents = [
    DependentModel(
      id: 1,
      fullName: 'Sophia Rostova',
      relationship: 'Child (Daughter)',
      dob: '2020-04-10',
      bloodGroup: 'A+',
      gender: 'Female',
      allergies: ['Peanuts', 'Penicillin'],
      chronicConditions: 'Mild seasonal pollen allergy',
      lastVitalsCheck: 'Today, 9:00 AM',
      pendingVaccinesCount: 1,
      activeMedicationsCount: 2,
    ),
    DependentModel(
      id: 2,
      fullName: 'Eleanor Rostova',
      relationship: 'Elderly Parent (Mother)',
      dob: '1958-11-23',
      bloodGroup: 'O+',
      gender: 'Female',
      allergies: ['Sulfa Drugs'],
      chronicConditions: 'Mild Osteopenia, Hypertension (Controlled)',
      lastVitalsCheck: 'Yesterday, 6:30 PM',
      pendingVaccinesCount: 0,
      activeMedicationsCount: 3,
    ),
  ];

  static final List<MedicationModel> medications = [
    MedicationModel(
      id: 1,
      dependentId: 1,
      name: 'Amoxicillin Pediatric Suspension',
      dosage: '250mg / 5mL',
      frequency: 'Twice Daily',
      timeOfDay: '8:00 AM & 8:00 PM',
      instructions: 'Take with milk or breakfast. Complete 7-day course.',
      prescribedBy: 'Dr. Sarah Jenkins',
      startDate: '2026-09-18',
      endDate: '2026-09-25',
      isTakenToday: true,
      lastTakenTimestamp: 'Today, 8:15 AM',
    ),
    MedicationModel(
      id: 2,
      dependentId: 1,
      name: 'Children’s Chewable Multivitamin + Zinc',
      dosage: '1 Tablet Daily',
      frequency: 'Once Daily',
      timeOfDay: '1:00 PM (Lunch)',
      instructions: 'Chew thoroughly after meal.',
      prescribedBy: 'Pediatric Care Center',
      startDate: '2026-08-01',
      isTakenToday: false,
    ),
    MedicationModel(
      id: 3,
      dependentId: 2,
      name: 'Amlodipine Besylate',
      dosage: '5mg Tablet',
      frequency: 'Once Daily',
      timeOfDay: '8:00 AM (Morning)',
      instructions: 'Take on empty stomach with water. Monitor BP.',
      prescribedBy: 'Dr. Liam Vance',
      startDate: '2026-01-10',
      isTakenToday: true,
      lastTakenTimestamp: 'Today, 8:05 AM',
    ),
    MedicationModel(
      id: 4,
      dependentId: 2,
      name: 'Calcium Citrate + Vitamin D3',
      dosage: '600mg / 400 IU',
      frequency: 'Twice Daily',
      timeOfDay: '12:00 PM & 7:00 PM',
      instructions: 'Take with meals to support bone density.',
      prescribedBy: 'Dr. Maya Patel',
      startDate: '2026-03-15',
      isTakenToday: false,
    ),
  ];

  static final List<VaccinationModel> vaccinations = [
    VaccinationModel(
      id: 1,
      dependentId: 1,
      vaccineName: 'MMR Booster (2nd Dose)',
      targetDisease: 'Measles, Mumps, Rubella',
      recommendedAge: '4–6 Years',
      dueDate: '2026-10-15',
      status: 'Due Soon',
      notes: 'Scheduled at Valley Pediatrics Clinic.',
    ),
    VaccinationModel(
      id: 2,
      dependentId: 1,
      vaccineName: 'DTaP (5th Dose)',
      targetDisease: 'Diphtheria, Tetanus, Pertussis',
      recommendedAge: '4–6 Years',
      dueDate: '2026-06-12',
      status: 'Completed',
      administeredDate: '2026-06-12',
      administeredBy: 'Valley Pediatrics',
      batchNumber: 'DT-89301-B',
    ),
    VaccinationModel(
      id: 3,
      dependentId: 1,
      vaccineName: 'Inactivated Polio (IPV 4th Dose)',
      targetDisease: 'Poliomyelitis',
      recommendedAge: '4–6 Years',
      dueDate: '2026-06-12',
      status: 'Completed',
      administeredDate: '2026-06-12',
      administeredBy: 'Valley Pediatrics',
      batchNumber: 'IPV-44129',
    ),
    VaccinationModel(
      id: 4,
      dependentId: 2,
      vaccineName: 'Shingrix (Herpes Zoster Dose 2)',
      targetDisease: 'Shingles',
      recommendedAge: 'Adults 50+',
      dueDate: '2026-05-10',
      status: 'Completed',
      administeredDate: '2026-05-10',
      administeredBy: 'City Health Immunization',
      batchNumber: 'SH-99210',
    ),
    VaccinationModel(
      id: 5,
      dependentId: 2,
      vaccineName: 'Annual Quadrivalent Influenza',
      targetDisease: 'Influenza A & B',
      recommendedAge: 'Annual (Autumn)',
      dueDate: '2026-10-30',
      status: 'Upcoming',
    ),
  ];

  static final List<PatientModel> patients = [
    PatientModel(
      id: 1,
      fullName: 'Elena Rostova',
      email: 'elena@femsphere.health',
      age: '28 yrs',
      bloodGroup: 'A+',
      healthTwinScore: 92,
      primaryConcern: 'Hormonal Wellness & Luteal Fatigue',
      lastVisit: 'Sep 15, 2026',
      lifeStage: 'Reproductive Age (25–39)',
      sharedRecordsCount: 4,
      riskCategory: 'Optimal',
    ),
    PatientModel(
      id: 2,
      fullName: 'Maya Lin',
      email: 'maya.lin@email.com',
      age: '34 yrs',
      bloodGroup: 'B+',
      healthTwinScore: 84,
      primaryConcern: 'Pre-conception Screening & Iron Levels',
      lastVisit: 'Aug 29, 2026',
      lifeStage: 'Reproductive Age (25–39)',
      sharedRecordsCount: 3,
      riskCategory: 'Low Risk',
    ),
    PatientModel(
      id: 3,
      fullName: 'Clara Oswald',
      email: 'clara.o@outlook.com',
      age: '48 yrs',
      bloodGroup: 'O+',
      healthTwinScore: 78,
      primaryConcern: 'Perimenopause Vasomotor Symptoms',
      lastVisit: 'Aug 14, 2026',
      lifeStage: 'Perimenopause (40–49)',
      sharedRecordsCount: 6,
      riskCategory: 'Moderate',
    ),
    PatientModel(
      id: 4,
      fullName: 'Aaliyah Khan',
      email: 'aaliyah.k@gmail.com',
      age: '22 yrs',
      bloodGroup: 'AB+',
      healthTwinScore: 95,
      primaryConcern: 'Athletic Nutrition & Cycle Periodicity',
      lastVisit: 'Jul 20, 2026',
      lifeStage: 'Young Adult (18–24)',
      sharedRecordsCount: 2,
      riskCategory: 'Optimal',
    ),
  ];

  static final List<ConsultationModel> consultations = [
    ConsultationModel(
      id: 1,
      patientId: 1,
      patientName: 'Elena Rostova',
      patientAge: '28 yrs',
      date: '2026-09-15',
      chiefComplaint: 'Luteal phase fatigue, minor sleep disturbances 3 days prior to menses.',
      clinicalDiagnosis: 'Physiological Luteal Shift with Mild Magnesium Depletion',
      clinicalNotes: 'Endocrine panel demonstrates normal luteinizing hormone and FSH ratios. Progesterone peak adequate at 14.2 ng/mL. Advised on evening magnesium glycinate and targeted hydration.',
      prescriptions: [
        DigitalPrescriptionItem(
          medication: 'Magnesium Glycinate',
          dosage: '350mg',
          frequency: 'Once Daily at Bedtime',
          durationDays: '60',
          instructions: 'Take 30 minutes before sleep with water.',
        ),
        DigitalPrescriptionItem(
          medication: 'Vitamin B-Complex (Active Coenzymes)',
          dosage: '1 Capsule',
          frequency: 'Once Daily',
          durationDays: '30',
          instructions: 'Take with morning breakfast.',
        ),
      ],
      followUpRecommendation: 'Check-in via Telehealth in 60 days.',
      status: 'Completed',
    ),
    ConsultationModel(
      id: 2,
      patientId: 2,
      patientName: 'Maya Lin',
      patientAge: '34 yrs',
      date: '2026-08-29',
      chiefComplaint: 'Pre-conception counseling, ferritin levels review.',
      clinicalDiagnosis: 'Mild Iron Deficiency without Anemia (Ferritin 22 ng/mL)',
      clinicalNotes: 'Hemoglobin stable at 12.8 g/dL. Recommended gentle oral iron supplement paired with Vitamin C.',
      prescriptions: [
        DigitalPrescriptionItem(
          medication: 'Ferrous Bisglycinate Chelate',
          dosage: '28mg Elemental Iron',
          frequency: 'Alternate Days (Mon/Wed/Fri)',
          durationDays: '45',
          instructions: 'Take on empty stomach with citrus juice.',
        ),
      ],
      followUpRecommendation: 'Repeat ferritin test in 8 weeks.',
      status: 'Completed',
    ),
  ];

  static final List<ArticleModel> articles = [
    ArticleModel(
      id: 1,
      title: 'Mastering the 4 Menstrual Phases: Fuel Your Bio-Rhythm',
      category: 'Reproductive Health',
      readTime: '5 min read',
      author: 'Dr. Sarah Jenkins',
      date: 'Sep 18, 2026',
      summary: 'A deep dive into the Follicular, Ovulatory, Luteal, and Menstrual phases and how your metabolic rate changes.',
      content: 'During the follicular phase, estrogen rises, boosting energy, insulin sensitivity, and strength endurance. In the luteal phase, progesterone elevates resting body temperature by 0.5°C and shifts macro utilization toward fats. Syncing workouts and nutrition to these transitions optimizes hormonal balance.',
      isPublished: true,
      views: 890,
    ),
    ArticleModel(
      id: 2,
      title: 'The AI Health Twin: How Predictive Biomarkers Prevent Chronic Fatigue',
      category: 'AI Health Twin',
      readTime: '6 min read',
      author: 'FemSphere Research Team',
      date: 'Sep 14, 2026',
      summary: 'How combining heart rate variability, sleep stages, and basal temperature creates a continuous biological digital twin.',
      content: 'Traditional medicine is reactive; FemSphere AI Health Twin analyzes micro-fluctuations in vital signs to predict fatigue, cycle deviations, and nutrient deficiencies 5 to 7 days before physical symptoms manifest.',
      isPublished: true,
      views: 1420,
    ),
    ArticleModel(
      id: 3,
      title: 'Pediatric Vaccine Readiness: Essential Guidelines for Caregivers',
      category: 'Pediatrics',
      readTime: '4 min read',
      author: 'Valley Pediatrics Medical Staff',
      date: 'Sep 02, 2026',
      summary: 'Timelines and pre-appointment preparation tips for kindergarten and school booster immunizations.',
      content: 'Keep a digital immunization record updated. Ensure the child is well-hydrated and fed prior to booster shots. Cool compresses help soothe local injection site tenderness.',
      isPublished: true,
      views: 610,
    ),
  ];

  static final List<NotificationModel> notifications = [
    NotificationModel(
      id: 1,
      title: '🩸 Menstrual Phase Forecast',
      message: 'Your menstrual cycle is projected to begin in 3 days. Hydrate and prioritize gentle mobility exercises.',
      category: 'Period Alert',
      timestamp: '10 mins ago',
      isRead: false,
    ),
    NotificationModel(
      id: 2,
      title: '💊 Medication Reminder for Sophia',
      message: 'Amoxicillin Pediatric Suspension (250mg) is scheduled for 8:00 PM tonight.',
      category: 'Medication',
      timestamp: '2 hours ago',
      isRead: false,
    ),
    NotificationModel(
      id: 3,
      title: '🩺 Appointment Confirmed',
      message: 'Video Consultation with Dr. Sarah Jenkins confirmed for Oct 15 at 10:30 AM.',
      category: 'Appointment',
      timestamp: 'Yesterday',
      isRead: true,
    ),
    NotificationModel(
      id: 4,
      title: '✨ AI Twin Health Score Updated',
      message: 'Your weekly health twin bio-score increased to 92/100 following optimal sleep continuity.',
      category: 'AI Health Twin',
      timestamp: '2 days ago',
      isRead: true,
    ),
  ];

  static final List<Map<String, dynamic>> adminUsers = [
    {
      'id': 1,
      'fullName': 'Elena Rostova',
      'email': 'elena@femsphere.health',
      'role': 'User (Female)',
      'status': 'Active',
      'joinedDate': '2026-01-15',
      'lastActive': 'Just now',
    },
    {
      'id': 2,
      'fullName': 'Dr. Sarah Jenkins',
      'email': 'sarah.jenkins@femsphere.health',
      'role': 'Doctor',
      'status': 'Active',
      'license': 'MD-892401',
      'approvalStatus': 'Approved',
      'joinedDate': '2026-02-01',
      'lastActive': '12 mins ago',
    },
    {
      'id': 3,
      'fullName': 'Marcus Rostova',
      'email': 'marcus.caregiver@femsphere.health',
      'role': 'Caregiver',
      'status': 'Active',
      'dependentsCount': 2,
      'joinedDate': '2026-03-10',
      'lastActive': '1 hour ago',
    },
    {
      'id': 4,
      'fullName': 'Dr. Robert Thorne',
      'email': 'robert.thorne@metrohealth.org',
      'role': 'Doctor',
      'status': 'Pending Approval',
      'license': 'MD-991204',
      'approvalStatus': 'Pending',
      'specialty': 'Cardiology & Reproductive Health',
      'joinedDate': '2026-09-20',
      'lastActive': 'Today',
    },
    {
      'id': 5,
      'fullName': 'Sophia Chen',
      'email': 'sophia.c@gmail.com',
      'role': 'User (Female)',
      'status': 'Active',
      'joinedDate': '2026-05-19',
      'lastActive': '3 days ago',
    },
    {
      'id': 6,
      'fullName': 'David Vance',
      'email': 'david.vance@caregiver.org',
      'role': 'Caregiver',
      'status': 'Suspended',
      'dependentsCount': 1,
      'joinedDate': '2026-04-12',
      'lastActive': '2 weeks ago',
    },
  ];
}
